### ISSUE TITLE
Update NPM packages [React.js Beginners]

### ISSUE THREAD

**Issue by ashokdey** [ashokdey/react-invoice#1]
Do the following:

- [x] Update the packages
- [x] Make sure the app is running as expected
- [x] Check for **npn audit** as well
- [x] Only open PR if the app is running perfectly

**Comment by Mahesh419** [comment]
I would like to work on this.

**Comment by ashokdey** [comment]
I have assigned you this issue @Mahesh419, you got 4 hrs to do this.

**Comment by ashokdey** [comment]
#2 closes this issue.
